# workflow name
name: Hexo Blog CI

# main branch on push, auto run
on: 
  push:
    branches:
      - main
    paths:
      - src/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@main

      # 使用 node:10
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: npm install
        run: |
          sudo npm install -g hexo-cli
          cd src && npm install
      - name: Build
        run: |
          cd src && hexo genereate

      - name: Deploy to ecs server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: $GITHUB_ACTION_PATH/src/public/
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: "root"
          TARGET: "/data/hexo/"
